# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.41.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
