name: Snyk OS Code Scan

on:
  push
jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Node v14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: false
        with:
          command: code test
          args: --sarif --sarif-file-output=snyk_scan.sarif 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif-report
          path: snyk.sarif
